# docker-compose.yml

version: '3.8'

services:
  app:
    build: .
    restart: always
    volumes:
      - .:/app
    command: python manage.py run
    ports:
      - "8080:8080"
    environment:
      BACKEND_PORT: 8080
      BACKEND_HOST: 0.0.0.0
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecogram
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecogram
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    expose:
      - "5432"
volumes:
  postgres_data:
